CC=g++
SRCS = testDriver.cpp Creature.hpp Creature.cpp Medusa.hpp Medusa.cpp Dice.hpp Dice.cpp Barbarian.hpp Barbarian.cpp Vampire.hpp Vampire.cpp BlueMen.hpp BlueMen.cpp HarryPotter.hpp HarryPotter.cpp

all: ${SRCS}
	${CC} ${CFLAGS} ${SRCS} -o assignment3
clean:
	rm -rf *.o assignment3
