CC=g++
SRCS = main.cpp PressRoom.hpp PressRoom.cpp GuestBath.hpp GuestBath.cpp Door.hpp Door.cpp SittingArea.hpp SittingArea.cpp MasterBedroom.hpp MasterBedroom.cpp Inventory.hpp Inventory.cpp Player.hpp Player.cpp Room.hpp Room.cpp Game.hpp Game.cpp 

all: ${SRCS}
	${CC} ${CFLAGS} ${SRCS} -o final
clean:
	rm -rf *.o final